name: Run SonarLint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  # You can specify 'zulu', 'adopt', 'temurin', etc.

      - name: Install Maven dependencies
        run: mvn install -DskipTests

      - name: Run SonarLint
        run: mvn sonarlint:sonarlint
